import type { CatalogExercise } from "./exerciseCatalog";

export const CROSSFIT_CATALOG: CatalogExercise[] = [
  // Weightlifting
  {
    id: "cf-wl-01",
    name: "Back Squat",
    category: "Weightlifting",
    description: "Barra en espalda alta, pies al ancho de hombros. Bajá a profundidad y subí firme.",
  },
  {
    id: "cf-wl-02",
    name: "Front Squat",
    category: "Weightlifting",
    description: "Barra al frente sobre los deltoides, codos altos. Bajá con torso erguido y subí.",
  },
  {
    id: "cf-wl-03",
    name: "Overhead Squat",
    category: "Weightlifting",
    description: "Agarre ancho, barra sobre la cabeza durante todo el descenso. Bajá a profundidad con equilibrio.",
  },
  {
    id: "cf-wl-04",
    name: "Deadlift",
    category: "Weightlifting",
    description: "Pies al ancho de cadera, barra cerca de las tibias. Levantá extendiendo cadera y rodillas a la vez.",
  },
  {
    id: "cf-wl-05",
    name: "Sumo Deadlift High Pull",
    category: "Weightlifting",
    description: "Agarre amplio, tiré de la barra a la altura del mentón extendiendo cadera y codos.",
  },
  {
    id: "cf-wl-06",
    name: "Clean",
    category: "Weightlifting",
    description: "Tirá de la barra desde el piso a los hombros en un movimiento, recepción frontal.",
  },
  {
    id: "cf-wl-07",
    name: "Power Clean",
    category: "Weightlifting",
    description: "Tirá de la barra desde arriba de las rodillas a los hombros, recepción en squat parcial.",
  },
  {
    id: "cf-wl-08",
    name: "Hang Clean",
    category: "Weightlifting",
    description: "Tirá de la barra desde la posición colgada al muslo hasta los hombros, recepción frontal.",
  },
  {
    id: "cf-wl-09",
    name: "Clean & Jerk",
    category: "Weightlifting",
    description: "Clean seguido de jerk: arriba de la cabeza con brazos extendidos y pies firmes.",
  },
  {
    id: "cf-wl-10",
    name: "Snatch",
    category: "Weightlifting",
    description: "Tirá de la barra desde el piso directamente arriba de la cabeza en un movimiento amplio.",
  },
  {
    id: "cf-wl-11",
    name: "Power Snatch",
    category: "Weightlifting",
    description: "Tirá de la barra desde arriba de las rodillas directamente arriba de la cabeza.",
  },
  {
    id: "cf-wl-12",
    name: "Hang Snatch",
    category: "Weightlifting",
    description: "Tirá de la barra desde la posición colgada al muslo hasta arriba de la cabeza.",
  },
  {
    id: "cf-wl-13",
    name: "Thruster",
    category: "Weightlifting",
    description: "Front squat seguido de push press: bajá y empujá arriba usando piernas y hombros.",
  },
  {
    id: "cf-wl-14",
    name: "Push Press",
    category: "Weightlifting",
    description: "Barra en hombros, dip leve y empujá arriba sin split, recepción con pies juntos.",
  },
  {
    id: "cf-wl-15",
    name: "Push Jerk",
    category: "Weightlifting",
    description: "Barra en hombros, dip leve y empujá arriba con un paso de split, recepción con un pie adelante.",
  },
  {
    id: "cf-wl-16",
    name: "Split Jerk",
    category: "Weightlifting",
    description: "Igual que push jerk, pero con split más profundo y bloqueo firme arriba.",
  },

  // Gymnastics
  {
    id: "cf-gy-01",
    name: "Pull-up",
    category: "Gymnastics",
    description: "Agarre prono sobre la barra. Tirá del pecho hasta superar la barra y bajá controlado.",
  },
  {
    id: "cf-gy-02",
    name: "Chest-to-Bar Pull-up",
    category: "Gymnastics",
    description: "Igual que pull-up pero llevando el pecho a tocar la barra con dorsales activos.",
  },
  {
    id: "cf-gy-03",
    name: "Muscle-up",
    category: "Gymnastics",
    description: "Pull-up con transición: pasá la barra por encima con codos y pecho sobre anillos o barra.",
  },
  {
    id: "cf-gy-04",
    name: "Ring Dip",
    category: "Gymnastics",
    description: "En anillos, bajá flexionando codos hasta el paralelo y empujá arriba estabilizando.",
  },
  {
    id: "cf-gy-05",
    name: "Handstand Push-up",
    category: "Gymnastics",
    description: "En pared o libres, invertí y bajá flexionando codos hasta el piso, empujá arriba.",
  },
  {
    id: "cf-gy-06",
    name: "Handstand Walk",
    category: "Gymnastics",
    description: "En parada de manos, caminá con manos alternando, cuerpo alineado y abdomen firme.",
  },
  {
    id: "cf-gy-07",
    name: "Toes-to-Bar",
    category: "Gymnastics",
    description: "Colgado, subí piernas rectas hasta tocar la barra con los dedos de los pies.",
  },
  {
    id: "cf-gy-08",
    name: "Knees-to-Elbows",
    category: "Gymnastics",
    description: "Colgado, subí rodillas hasta los codos contrayendo abdomen sin balancear.",
  },
  {
    id: "cf-gy-09",
    name: "Pistol Squat",
    category: "Gymnastics",
    description: "Una pierna extendida al frente, la otra flexionada. Bajá a profundidad y subí sin apoyo.",
  },
  {
    id: "cf-gy-10",
    name: "Air Squat",
    category: "Gymnastics",
    description: "Pies al ancho de hombros, bajá a profundidad manteniendo talones en el piso.",
  },
  {
    id: "cf-gy-11",
    name: "Push-up",
    category: "Gymnastics",
    description: "Manos al piso, cuerpo en línea. Bajá el pecho y empujá firme manteniendo abdomen contraído.",
  },
  {
    id: "cf-gy-12",
    name: "Rope Climb",
    category: "Gymnastics",
    description: "Tirá de la cuerda solo con brazos y manos hasta tocar el suelo desde arriba.",
  },
  {
    id: "cf-gy-13",
    name: "L-Sit",
    category: "Gymnastics",
    description: "En paralelas o suelo, mantené cadera elevada con piernas extendidas al frente en L.",
  },
  {
    id: "cf-gy-14",
    name: "Ring Row",
    category: "Gymnastics",
    description: "Anillos a la altura de la cadera, cuerpo en línea. Tirá del pecho a los anillos horizontal.",
  },
  {
    id: "cf-gy-15",
    name: "GHD Sit-up",
    category: "Gymnastics",
    description: "En máquina GHD, bajá atrás y subí hasta la vertical contrayendo abdomen.",
  },

  // Monostructural/Cardio
  {
    id: "cf-mo-01",
    name: "Row",
    category: "Monostructural/Cardio",
    description: "Remo en máquina: piernas primero, después torso, finalizá con brazos. Invertí al volver.",
  },
  {
    id: "cf-mo-02",
    name: "Assault Bike",
    category: "Monostructural/Cardio",
    description: "Bicicleta de aire: pedaleo con brazos y piernas. Distribuí el esfuerzo durante todo el tiempo.",
  },
  {
    id: "cf-mo-03",
    name: "Ski Erg",
    category: "Monostructural/Cardio",
    description: "Ski Erg: tirones con brazos desde arriba, usando abdomen y glúteos para estabilizar.",
  },
  {
    id: "cf-mo-04",
    name: "Run",
    category: "Monostructural/Cardio",
    description: "Carrera constante o intervalos, controlá el ritmo y la pisada según el bloque.",
  },
  {
    id: "cf-mo-05",
    name: "Double-Under",
    category: "Monostructural/Cardio",
    description: "Doble salto: la cuerda pasa dos veces por debajo en cada salto, con muñecas activas.",
  },
  {
    id: "cf-mo-06",
    name: "Single-Under",
    category: "Monostructural/Cardio",
    description: "Saltá la cuerda una vez por salto, ritmo constante y pies juntos.",
  },
  {
    id: "cf-mo-07",
    name: "Burpee",
    category: "Monostructural/Cardio",
    description: "De pie a plancha, una flexión, salto al frente con manos arriba. Repetí sin pausa.",
  },
  {
    id: "cf-mo-08",
    name: "Burpee Box Jump Over",
    category: "Monostructural/Cardio",
    description: "Burpee con salto lateral sobre el cajón. Toca pecho al piso y salta al otro lado.",
  },
  {
    id: "cf-mo-09",
    name: "Wall Ball Shot",
    category: "Monostructural/Cardio",
    description: "Sentadilla con pelota medicinal al pecho y lanzamiento al punto alto en la pared.",
  },
  {
    id: "cf-mo-10",
    name: "Kettlebell Swing",
    category: "Monostructural/Cardio",
    description: "Kettlebell entre piernas, cadera atrás. Balanceá desde la cadera hasta altura de hombros.",
  },
  {
    id: "cf-mo-11",
    name: "Box Jump",
    category: "Monostructural/Cardio",
    description: "Saltá con ambos pies al cajón, cayendo suave con cadera atrás. Bajá firme y repetí.",
  },
  {
    id: "cf-mo-12",
    name: "Farmers Carry",
    category: "Monostructural/Cardio",
    description: "Dos mancuernas o pesas pesadas, caminá con torso erguido sin perder el ritmo.",
  },
  {
    id: "cf-mo-13",
    name: "Sled Push",
    category: "Monostructural/Cardio",
    description: "Empuje de trineo con carga, postura baja, paso constante sin levantar el torso.",
  },
  {
    id: "cf-mo-14",
    name: "Shuttle Run",
    category: "Monostructural/Cardio",
    description: "Carrera corta ida y vuelta entre dos líneas, aceleración y frenado en cada cambio.",
  },
];
