import type { CatalogExercise } from "./exerciseCatalog";

export const CROSSFIT_CATALOG: CatalogExercise[] = [
  // Weightlifting
  { id: "cf-wl-01", name: "Back Squat", category: "Weightlifting" },
  { id: "cf-wl-02", name: "Front Squat", category: "Weightlifting" },
  { id: "cf-wl-03", name: "Overhead Squat", category: "Weightlifting" },
  { id: "cf-wl-04", name: "Deadlift", category: "Weightlifting" },
  { id: "cf-wl-05", name: "Sumo Deadlift High Pull", category: "Weightlifting" },
  { id: "cf-wl-06", name: "Clean", category: "Weightlifting" },
  { id: "cf-wl-07", name: "Power Clean", category: "Weightlifting" },
  { id: "cf-wl-08", name: "Hang Clean", category: "Weightlifting" },
  { id: "cf-wl-09", name: "Clean & Jerk", category: "Weightlifting" },
  { id: "cf-wl-10", name: "Snatch", category: "Weightlifting" },
  { id: "cf-wl-11", name: "Power Snatch", category: "Weightlifting" },
  { id: "cf-wl-12", name: "Hang Snatch", category: "Weightlifting" },
  { id: "cf-wl-13", name: "Thruster", category: "Weightlifting" },
  { id: "cf-wl-14", name: "Push Press", category: "Weightlifting" },
  { id: "cf-wl-15", name: "Push Jerk", category: "Weightlifting" },
  { id: "cf-wl-16", name: "Split Jerk", category: "Weightlifting" },

  // Gymnastics
  { id: "cf-gy-01", name: "Pull-up", category: "Gymnastics" },
  { id: "cf-gy-02", name: "Chest-to-Bar Pull-up", category: "Gymnastics" },
  { id: "cf-gy-03", name: "Muscle-up", category: "Gymnastics" },
  { id: "cf-gy-04", name: "Ring Dip", category: "Gymnastics" },
  { id: "cf-gy-05", name: "Handstand Push-up", category: "Gymnastics" },
  { id: "cf-gy-06", name: "Handstand Walk", category: "Gymnastics" },
  { id: "cf-gy-07", name: "Toes-to-Bar", category: "Gymnastics" },
  { id: "cf-gy-08", name: "Knees-to-Elbows", category: "Gymnastics" },
  { id: "cf-gy-09", name: "Pistol Squat", category: "Gymnastics" },
  { id: "cf-gy-10", name: "Air Squat", category: "Gymnastics" },
  { id: "cf-gy-11", name: "Push-up", category: "Gymnastics" },
  { id: "cf-gy-12", name: "Rope Climb", category: "Gymnastics" },
  { id: "cf-gy-13", name: "L-Sit", category: "Gymnastics" },
  { id: "cf-gy-14", name: "Ring Row", category: "Gymnastics" },
  { id: "cf-gy-15", name: "GHD Sit-up", category: "Gymnastics" },

  // Monostructural/Cardio
  { id: "cf-mo-01", name: "Row", category: "Monostructural/Cardio" },
  { id: "cf-mo-02", name: "Assault Bike", category: "Monostructural/Cardio" },
  { id: "cf-mo-03", name: "Ski Erg", category: "Monostructural/Cardio" },
  { id: "cf-mo-04", name: "Run", category: "Monostructural/Cardio" },
  { id: "cf-mo-05", name: "Double-Under", category: "Monostructural/Cardio" },
  { id: "cf-mo-06", name: "Single-Under", category: "Monostructural/Cardio" },
  { id: "cf-mo-07", name: "Burpee", category: "Monostructural/Cardio" },
  { id: "cf-mo-08", name: "Burpee Box Jump Over", category: "Monostructural/Cardio" },
  { id: "cf-mo-09", name: "Wall Ball Shot", category: "Monostructural/Cardio" },
  { id: "cf-mo-10", name: "Kettlebell Swing", category: "Monostructural/Cardio" },
  { id: "cf-mo-11", name: "Box Jump", category: "Monostructural/Cardio" },
  { id: "cf-mo-12", name: "Farmers Carry", category: "Monostructural/Cardio" },
  { id: "cf-mo-13", name: "Sled Push", category: "Monostructural/Cardio" },
  { id: "cf-mo-14", name: "Shuttle Run", category: "Monostructural/Cardio" },
];
